"""empty message

Revision ID: 7fff2532b654
Revises: 5f3166fb28de
Create Date: 2025-05-29 01:32:23.139201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fff2532b654'
down_revision = '5f3166fb28de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rate', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
